name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # - name: Run tests
    #   run: |
    #     pytest tests/tests.py

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Check Docker builder info
      run: docker buildx ls

    - name: Reset Docker to classic builder (if needed)
      run: |
        docker buildx stop default || true
        docker buildx rm default || true
        echo "Reset Docker builder to classic"

    - name: Build Docker image
      run: |  
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mlops-model1:latest .
        
    - name: Push Docker image
      run: |
        # docker tag post-assessment ${{ secrets.DOCKERHUB_USERNAME }}/post-assessment:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlops-model1:latest
