name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Run tests
    #   run: |
    #     pytest tests/tests.py

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    # - name: Build Docker image using buildx
    #   run: |
    #     docker buildx create --use --name mybuilder || echo "Builder exists"
    #     docker buildx build --platform linux/amd64 \
    #       -t ${{ secrets.DOCKERHUB_USERNAME }}/post-assessment:latest \
    #       --push .

    - name: Disable Buildx
      run: |
          export DOCKER_CLI_EXPERIMENTAL=disabled
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/post-assessment:latest .

    # - name: Build Docker image
    #   run: |  
    #     docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/post-assessment:latest .
        
    - name: Push Docker image
      run: |
        # docker tag post-assessment ${{ secrets.DOCKERHUB_USERNAME }}/post-assessment:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/post-assessment:latest
