name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set up Docker CLI (disable buildx)
      run: |
        docker build --version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # - name: Run tests
    #   run: |
    #     pytest tests/tests.py

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |  
        docker image build -t ${{ secrets.DOCKERHUB_USERNAME }}/post-assessment:latest .
        
    - name: Push Docker image
      run: |
        # docker tag post-assessment ${{ secrets.DOCKERHUB_USERNAME }}/post-assessment:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/post-assessment:latest
